FROM php:7.4.20-apache

RUN apt update && \
    apt -y install less && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* && \
    pecl install apcu-5.1.20 && \ 
    pecl install zip-1.19.3 && \
    docker-php-ext-install devel pdo gd mcrypt fedora-autoloader pear process xmlrpc imap


COPY ./php/php.ini /usr/local/etc/php/php.ini

